document.writeln("<script type=\"text\/javascript\"><!--");
document.writeln("google_ad_client = \"pub-5977682010997732\";");
document.writeln("\/* 468x15, ´´½¨ÓÚ 08-7-29 *\/");
document.writeln("google_ad_slot = \"6233349099\";");
document.writeln("google_ad_width = 468;");
document.writeln("google_ad_height = 15;");
document.writeln("\/\/-->");
document.writeln("<\/script>");
document.writeln("<script type=\"text\/javascript\"");
document.writeln("src=\"http:\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js\">");
document.writeln("<\/script>");