document.writeln("<script type=\"text\/javascript\"><!--");
document.writeln("google_ad_client = \"pub-5977682010997732\";");
document.writeln("\/* 336x280, ´´½¨ÓÚ 08-7-26 *\/");
document.writeln("google_ad_slot = \"8221152630\";");
document.writeln("google_ad_width = 336;");
document.writeln("google_ad_height = 280;");
document.writeln("\/\/-->");
document.writeln("<\/script>");
document.writeln("<script type=\"text\/javascript\"");
document.writeln("src=\"http:\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js\">");
document.writeln("<\/script>");