document.write("<p class='gray'>");
document.write("	<span class='big'>1</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9032984_0_0.html' target=_blank title=\"高手终于在这里现身了！我快笑抽了·吃着东西的别进\">高手终于在这里现身了！我快笑.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span class='big'>2</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9044995_0_0.html' target=_blank title=\"有人管么？连云港广电总局网站快变成黄色网站了！【连载】【11-28更新】\">有人管么？连云港广电总局网站.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span class='big'>3</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9042733_0_0.html' target=_blank title=\"静香的入浴场景及大熊的偷窥分析\">静香的入浴场景及大熊的偷窥分析</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>4</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9041731_0_0.html' target=_blank title=\"我在易初莲花用优乐美调戏了一下收银台MM！！！！\">我在易初莲花用优乐美调戏了一.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>5</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9041225_0_0.html' target=_blank title=\"本大小姐是来秀新买的宝马的，穷人请让开\">本大小姐是来秀新买的宝马的，.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>6</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9040473_0_0.html' target=_blank title=\"猫扑美腿大赛私人整理珍藏版\">猫扑美腿大赛私人整理珍藏版</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>7</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9041444_0_0.html' target=_blank title=\"八次暴力血案：山东野蛮拆迁又出命案\">八次暴力血案：山东野蛮拆迁又.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>8</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9042808_0_0.html' target=_blank title=\"连媒体都公然造假,我们还能相信谁?\">连媒体都公然造假,我们还能相.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>9</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9046425_0_0.html' target=_blank title=\"心痒难忍,小女参加美腿大赛顺便卖身求个职【召集】\">心痒难忍,小女参加美腿大赛顺.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>10</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9043726_0_0.html' target=_blank title=\"啊！我的毛湿了（一个色女有才的日记）\">啊！我的毛湿了（一个色女有才.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>11</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_8753429_0_0.html' target=_blank title=\"有多少男人喜欢平胸的女人（召集）\">有多少男人喜欢平胸的女人（召.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>12</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9041076_0_0.html' target=_blank title=\"香港6中学生“五王一后”性爱游戏视频被传上网\">香港6中学生“五王一后”性爱.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>13</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9045030_0_0.html' target=_blank title=\"姚明赛后大爆粗口泄怒骂主帅(视频)\">姚明赛后大爆粗口泄怒骂主帅(.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>14</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9043428_0_0.html' target=_blank title=\"怪短信专整“山寨机”不抠下电池振动不止\">怪短信专整“山寨机”不抠下电.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>15</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9041239_0_0.html' target=_blank title=\"网友因发帖揭露政.府黑幕被追捕至今逃亡在外\">网友因发帖揭露政.府黑幕被追.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>16</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9044256_0_0.html' target=_blank title=\"无耻的见多了,但像中国电信这样的老流氓还是第一个!【原创】\">无耻的见多了,但像中国电信这.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>17</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9045226_0_0.html' target=_blank title=\"东北某高校女大学生暴力围殴同学<br>\">东北某高校女大学生暴力围殴同.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>18</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9044411_0_0.html' target=_blank title=\"我是越南国防部长的女儿：来猫扑交朋友\">我是越南国防部长的女儿：来猫.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>19</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9042968_0_0.html' target=_blank title=\"抽筋的笑话大集合...囧rz!!!\">抽筋的笑话大集合...囧rz.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>20</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9045121_0_0.html' target=_blank title=\"暴强深夜性节目：这位妇女，你下面又……\">暴强深夜性节目：这位妇女，你.</a>");
document.write("</p>");
