document.write("<p class='gray'>");
document.write("	<span class='big'>1</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9007538_0_0.html' target=_blank title=\"这张相片在香港笑晕了16万人\">这张相片在香港笑晕了16万人</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span class='big'>2</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_8982756_0_0.html' target=_blank title=\"玲玲潜水许久,也想秀秀身材,七月拍的!【原创】\">玲玲潜水许久,也想秀秀身材,.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span class='big'>3</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9025637_0_0.html' target=_blank title=\"一个漂亮90后临死前的所做所为》\">一个漂亮90后临死前的所做所.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>4</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9020839_0_0.html' target=_blank title=\"猫扑美女秀出来之第二弹：美腿大赛开始\">猫扑美女秀出来之第二弹：美腿.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>5</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9029934_0_0.html' target=_blank title=\"据说这是历史上最KB的一个谜语，几乎没人答对【原创】\">据说这是历史上最KB的一个谜.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>6</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9032984_0_0.html' target=_blank title=\"高手终于在这里现身了！我快笑抽了·吃着东西的别进\">高手终于在这里现身了！我快笑.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>7</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9034582_0_0.html' target=_blank title=\"进来的彩票中奖率提升30％！！大家共勉&nbsp;早日中大奖\">进来的彩票中奖率提升30％！.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>8</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9027691_0_0.html' target=_blank title=\"小女生日求祝福,幸运楼层有大奖!【召集】\">小女生日求祝福,幸运楼层有大.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>9</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9041225_0_0.html' target=_blank title=\"本大小姐是来秀新买的宝马的，穷人请让开\">本大小姐是来秀新买的宝马的，.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>10</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9037667_0_0.html' target=_blank title=\"乙肝没有特效药！！媒体良知何在？【原创】\">乙肝没有特效药！！媒体良知何.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>11</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9031344_0_0.html' target=_blank title=\"世界各国军姿！中国最帅！！！！！！\">世界各国军姿！中国最帅！！！.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>12</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9025747_0_0.html' target=_blank title=\"我是卡帕女\">我是卡帕女</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>13</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9044995_0_0.html' target=_blank title=\"有人管么？连云港广电总局网站快变成黄色网站了！【连载】【11-28更新】\">有人管么？连云港广电总局网站.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>14</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9031325_0_0.html' target=_blank title=\"无敌气质美女—谁敢和我比素颜?【原创】\">无敌气质美女—谁敢和我比素颜.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>15</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9029124_0_0.html' target=_blank title=\"韩国开天辟地的搞笑历史剧《渊盖苏文》剧照\">韩国开天辟地的搞笑历史剧《渊.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>16</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9027637_0_0.html' target=_blank title=\"1年中跟15个男人发生关系，请求老公原谅【求助】\">1年中跟15个男人发生关系，.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>17</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9039142_0_0.html' target=_blank title=\"晒晒咱们公务员的福利(带图)\">晒晒咱们公务员的福利(带图)</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>18</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9031007_0_0.html' target=_blank title=\"〓斯特瑞克〓华裔美国大兵在伊拉克的战地日记\">〓斯特瑞克〓华裔美国大兵在伊.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>19</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9035817_0_0.html' target=_blank title=\"两只蝴蝶，70后大叔勇献雷人著作！\">两只蝴蝶，70后大叔勇献雷人.</a>");
document.write("</p>");
document.write("<p class='gray'>");
document.write("	<span>20</span>");
document.write("	<a href='http://dzh.mop.com/topic/readSub_9041444_0_0.html' target=_blank title=\"八次暴力血案：山东野蛮拆迁又出命案\">八次暴力血案：山东野蛮拆迁又.</a>");
document.write("</p>");
