document.writeln("<div id=\"top\">");
document.writeln("	<div id=\"header\">");
document.writeln("		<div class=\"t_r\">");
document.writeln("			<p><span id=\"Ylogin\" style=\"display:none\"><\/span> ");
document.writeln("			<span id=\"Nlogin\" style=\"display:none\"><\/span><\/p>");
document.writeln("			<p>嵌入式在线搜索：<input name=\"search\" id=\"search\" type=\"text\" class=\"input_s\" maxlength=\"100\" \/> ");
document.writeln("			    <select name=\"SelectType\" id=\"SelectType\">");
document.writeln("				    <option value=\"8\">综合<\/option>");
document.writeln("					<option value=\"0\">资讯<\/option>");
document.writeln("					<option value=\"1\">企业<\/option>");
document.writeln("					<option value=\"2\">产品<\/option>");
document.writeln("					<option value=\"3\">方案<\/option>");
document.writeln("					<option value=\"4\">论坛<\/option>");
document.writeln("					<option value=\"5\">Blog<\/option>");
document.writeln("					<option value=\"6\">下载<\/option>");
document.writeln("					<option value=\"7\">技术<\/option>");
document.writeln("			    <\/select>&nbsp;<input type=\"button\" value=\"搜索\" class=\"button\" onclick=\"searchT();\" \/><\/p>");
document.writeln("		<\/div>");
document.writeln("		<div class=\"logo\"><a href=\"http:\/\/www.mcuol.com\"><img src=\"http:\/\/www.mcuol.com\/images\/logo.jpg\" alt=\"嵌入式在线\" \/><\/a><\/div>");
document.writeln("	<\/div>");
document.writeln("	");
document.writeln("	<!--网站导航-->");
document.writeln("	<div id=\"nav\">");
document.writeln("		<ul>");
document.writeln("		  <li><a href=\"http:\/\/www.mcuol.com\/\" target=\"_blank\">首 页<\/a><\/li> ");
document.writeln("		  <li><a href=\"http:\/\/www.mcuol.com\/Solution\/\" target=\"_blank\">解决方案<\/a><\/li> ");
document.writeln("		  <li><a href=\"http:\/\/www.mcuol.com\/Download\/\" target=\"_blank\">资料下载<\/a><\/li> ");
document.writeln("		  <li><a href=\"http:\/\/bbs.mcuol.com\/\" target=\"_blank\" style='color:red;'>论 坛<\/a><\/li> ");
document.writeln("		  <li><a href=\"http:\/\/blog.mcuol.com\/\" target=\"_blank\">Blog<\/a><\/li> ");
document.writeln("		  <li><a href=\"http:\/\/job.mcuol.com\/\" target=\"_blank\" style='color:red;'>伯乐桥<\/a><\/li> ");
document.writeln("		  <li><a href=\"http:\/\/baike.mcuol.com\/\" target=\"_blank\" style='color:red;'>百 科<\/a><\/li> ");
document.writeln("		  <li><a href=\"http:\/\/company.mcuol.com\/Product\/\" target=\"_blank\">买 卖<\/a><\/li> ");
document.writeln("		  <li><a href=\"http:\/\/www.mcuol.com\/News\/\" target=\"_blank\">资 讯<\/a><\/li> ");
document.writeln("		  <li><a href=\"http:\/\/www.mcuol.com\/Tech\/\" target=\"_blank\">技术中心<\/a><\/li> ");
document.writeln("		  <li><a href=\"http:\/\/company.mcuol.com\/\" target=\"_blank\">厂 商<\/a><\/li> ");
document.writeln("		  <li><a href=\"http:\/\/bulo.mcuol.com\/\" target=\"_blank\">部 落<\/a><\/li> ");
document.writeln("		  <li><a href=\"http:\/\/search.mcuol.com\" target=\"_blank\">搜 索<\/a><\/li>");
document.writeln("	  <\/ul>");
document.writeln("	<\/div>");
document.writeln("<\/div>");